version: '3.4'

services:
  openqms:
    image: ${DOCKER_REGISTRY-}crealizeits/openqms:dev
    ports:
      - "80"
      - "443"
    labels:
      kompose.service.type: NodePort
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Temp1234
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Temp1234" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 10s